name: localhost-proxy

services:
  traefik:
    image: traefik:latest
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --api.insecure=true
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080" # Traefik dashboard (optional)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - localhost_net

volumes: {}

networks:
  localhost_net:
    external: true
